# Generated by Django 4.2.30 on 2026-05-07 22:49

from django.db import migrations, models
import django.db.models.deletion
import netbox_virtual_tour.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('floorplan', models.ImageField(blank=True, null=True, upload_to=netbox_virtual_tour.models._floorplan_path)),
                ('floorplan_width', models.PositiveIntegerField(default=0)),
                ('floorplan_height', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('published_data', models.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to=netbox_virtual_tour.models._scene_photo_path)),
                ('floorplan_x', models.FloatField(default=0.5)),
                ('floorplan_y', models.FloatField(default=0.5)),
                ('floorplan_rotation', models.FloatField(default=0.0)),
                ('default_yaw', models.FloatField(default=0.0)),
                ('default_pitch', models.FloatField(default=0.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='netbox_virtual_tour.virtualtour')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SceneLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaw', models.FloatField(default=0.0)),
                ('pitch', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('from_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='netbox_virtual_tour.scene')),
                ('to_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='netbox_virtual_tour.scene')),
            ],
            options={
                'unique_together': {('from_scene', 'to_scene')},
            },
        ),
    ]
